### ISSUE TITLE
look into proto-lens-jsonpb

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#109]
It's possible that this library could allow is to get away with less manual json definitions or `WrappedVal`s 

https://hackage.haskell.org/package/proto-lens-jsonpb

**Comment by IvantheTricourne** [comment]
https://github.com/tclem/proto-lens-jsonpb/blob/master/src/Data/ProtoLens/JSONPB/Class.hs#L224-L226

This function might help out with types with `String Fields` issues as described in #92.

**Comment by IvantheTricourne** [comment]
https://github.com/tclem/proto-lens-jsonpb/blob/master/src/Data/ProtoLens/JSONPB/Class.hs#L159-L162

This one should address the other 2 categories

**Comment by IvantheTricourne** [comment]
I should be able to give a pretty thorough pros/cons write up for this. 

See my WIP [branch](https://github.com/f-o-a-m/hs-abci/tree/json-pb)

**Comment by IvantheTricourne** [comment]
Given below, I don't think we benefit using this library. Aside from not having to worry about possible null values (i.e., because every PB instance is required to declare a default field value), we actually incur writing more boilerplate and manual JSON instances.

## CONS

* we cannot use generic deriving
* we must manually derive `FromJSONPB` instances via `(.:)` for any nullable type
* we cannot completely remove wrapped values: certain request types (i.e., `Query`) actually use string parameters (i.e., `height`); JSON-PB only allows for string to int parsing.

## PROS
* every nullable field must have a protolens `FieldDefault` instance (i.e., we don't have to handle `Null`s)
* every `FromJSON` instance just uses `(.:)` and not `(.?)`/`(.!=)`
* most `ToJSON` and `FromJSON` instances can be derived from the corresponding PB equivalent

**Comment by IvantheTricourne** [comment]
In a similar effort of trying to use generic JSON parsers, I've come to another conclusion:

We should only use this library if we find any value in encoding defaults inside of a `FieldDefault` versus directly in an Aeson parser:

```haskell
newtype Foo = Foo {..}

instance FromJSON Foo where
  parseJSON = withObject "Foo" $ \v -> Foo
    <$> v .:? "some_nullable_field" .!= someDefault
```

versus with PB:

```haskell
newtype Foo = Foo {..}

instance FromJSONPB NullableField where
  parseJSONPB = ...
instance FieldDefault NullableField where
  fieldDefault = someDefault

instance FromJSON Foo where
  parseJSON = withObject "Foo" $ \v -> Foo
    <$> v .: "some_nullable_field"
```
