### ISSUE TITLE
Docs don't instruct project set up

### ISSUE THREAD

**Issue by okwme** [f-o-a-m/kepler#230]
Docs are good at setting up important concepts before describing their use in the tutorial. Something the tutorial is missing is instructions for preparing your project in general. Basic instructions like: create a new working directory, create these folders, or instructions for creating any config, MAKE or dependency files that are needed for building a new project. I'm new to haskell so I'm not sure what exactly these kinds of instructions would look like, but going through the tutorial I see samples of code within specific files without instructions to create those files. 

this may feel a bit pedantic, but i think the name service tutorial for the sdk also serves as a good intro to working with golang in general (and same for the substrate docs for using rust). I don't think it's the responsibility of this tutorial to introduce haskell, but it would be good if a completely new haskell user could at least successfully create a working project by following instructions exactly.

**Comment by IvantheTricourne** [comment]
Hi,

I had an old issue I closed a while back to do something like this before working on a project that uses this lib. Just wanted to include a link to that issue here: https://github.com/f-o-a-m/kepler/issues/202, it might help out in some way.

The issue also has [this comment](https://github.com/f-o-a-m/kepler/issues/202#issuecomment-580497965) that describes how to add this project as a dep.

**Comment by kejace** [comment]
I will add a snippet to the installation instructions on how to setup a new project (using `stack`). I think that using this project as a springboard to haskell isn't quite possible; go-lang is a very simple language compared to haskell.
