### ISSUE TITLE
Add Store Handlers to query for entire arrays/lists

### ISSUE THREAD

**Issue by IvantheTricourne** [f-o-a-m/kepler#234]
The [Query Store](https://github.com/f-o-a-m/kepler/blob/175c1e7b6e0c61a1389fa9a8965dd04b9260ef11/hs-abci-sdk/src/Tendermint/SDK/BaseApp/Query/Store.hs#L88-L124) does not have a way to query for the entire stored array/list. Perhaps the same can be said for `Map`s as well.

The instance types should be something like:

```haskell
StoreQueryHandler (A.Array a) (QueryArgs ArrayKey -> Sem r (QueryResult [a]))
StoreQueryHandler (L.List a) (QueryArgs ListKey -> Sem r (QueryResult [a]))
```

If no key (i.e., `ArrayKey`, `ListKey`) is available for such an instance, maybe a query arg of `()` might work.

**Comment by IvantheTricourne** [comment]
Side note: if querying for the entire structure in store is something reserved for `Var`s (i.e., storing a map, array or list as a `Var` store type), then perhaps this isn't necessary.

**Comment by martyall** [comment]
You probably wouldn't want to expose this by default because these lists can be arbitrarily long (like in theory thousands of elements) and you don't want to ever try to serialize the whole thing. This style of default access by index only is the same as is done in ethereum, I think it's sufficient for now. 

It's possible to implement these kinds of queries by hand and include them in the query api, since both lists and arrays have a `toList` method
