### ISSUE TITLE
Generate full tendermint client using swagger.json

### ISSUE THREAD

**Issue by safareli** [f-o-a-m/kepler#47]
Opening this to track `omitempty` issue which would result in parse error if tendermint client we have is used against some go implementation which doens't set all props of types generated from proto files.

https://github.com/tendermint/tendermint/issues/3882 (PR https://github.com/tendermint/tendermint/pull/3889)

https://petstore.swagger.io/?url=https://raw.githubusercontent.com/tendermint/tendermint/master/docs/spec/rpc/swagger.yaml

https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/tendermint/tendermint/master/docs/spec/rpc/swagger.yaml

**Comment by martyall** [comment]
This would definitely be nice, I tried to write tests today for the example app using the RPC client and it's broken in ways I can't even really understand. here's an excerpt from what got printed 

```
RPC Request
{
    "jsonrpc": "2.0",
    "params": {
        "height": null,
        "path": "count",
        "data": "",
        "prove": false
    },
    "method": "abci_query",
    "id": 5559978479605965246
}
Response {responseStatus = Status {statusCode = 200, statusMessage = "OK"}, responseVersion = HTTP/1.1, responseHeaders = [("Content-Type","application/json"),("X-Server-Time","1565387031"),("Date","Fri, 09 Aug 2019 21:43:51 GMT"),("Content-Length","120")], responseBody = "{\n  \"jsonrpc\": \"2.0\",\n  \"id\": 5559978479605964800,\n  \"result\": {\n    \"response\": {\n      \"value\": \"AAAAAA==\"\n    }\n  }\n}", responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose}
RPC Response
{
    "result": {
        "response": {
            "value": "AAAAAA=="
        }
    },
    "jsonrpc": "2.0",
    "id": 5559978479605964800
}

```
As you can see, the value of the result doesn't even come close to [matching what we would expect](https://github.com/f-o-a-m/hs-abci/blob/example-app-tests/hs-tendermint-client/src/Network/Tendermint/Client.hs#L79) even if we account for the `omitEmpty` problem #46 . Also it appears that the bytestring values coming from tendermint-core are base64 encoded?

**Comment by martyall** [comment]
I just tried out the cli tool that is used to generate the client from a swagger file. You can find instructions [here](https://openapi-generator.tech/docs/installation.html) and an explanation of the options [here](https://github.com/jonschoning/swaggerpetstore-haskell-http-client#codegen-additional-properties-parameters).

Unfortunately the code it generates is pretty garbage. For example, instead of recognizing a pattern for general RPC messages, you get stuff like this for every method

```haskell
-- ** TxResponse
-- | TxResponse
data TxResponse = TxResponse
  { txResponseJsonrpc :: !(Text) -- ^ /Required/ "jsonrpc"
  , txResponseId :: !(Text) -- ^ /Required/ "id"
  , txResponseResult :: !(TxResponseResult) -- ^ /Required/ "result"
  } deriving (P.Show, P.Eq, P.Typeable)

-- ** TxResponseResult
-- | TxResponseResult
data TxResponseResult = TxResponseResult
  { txResponseResultHash :: !(Text) -- ^ /Required/ "hash"
  , txResponseResultHeight :: !(Text) -- ^ /Required/ "height"
  , txResponseResultIndex :: !(Double) -- ^ /Required/ "index"
  , txResponseResultTxResult :: !(TxSearchResponseResultTxResult) -- ^ /Required/ "tx_result"
  , txResponseResultTx :: !(Text) -- ^ /Required/ "tx"
  } deriving (P.Show, P.Eq, P.Typeable)

``` 

There are many other problems with it as well. I think it's similar to purescript-bridge and stuff like that. It would be nice to have as a stop-gap if the api is huge, but it's not great to keep around forever, especially for open source production level libraries. You can generate it yourself to have a look.

However, ideally they will make sure the swagger file is actually up to date and works, in which case we can just write the client library using the docs as a spec.

**Comment by safareli** [comment]
> As you can see, the value of the result doesn't even come close to matching what we would expect even if we account for the omitEmpty problem #46 

I think it does,

in `result` we have `response` (from ResultABCIQuery)

https://github.com/f-o-a-m/hs-abci/blob/48beac49ed758cf93fd445bb432c4e9bca9ee55c/hs-tendermint-client/src/Network/Tendermint/Client.hs#L79-L83


And in it, there is `value` (and from Response.Query)

https://github.com/f-o-a-m/hs-abci/blob/48beac49ed758cf93fd445bb432c4e9bca9ee55c/hs-abci-types/src/Network/ABCI/Types/Messages/Response.hs#L221-L249

tho Response.Query has the omitempty issue.

Because  `Response.Query` is constructed in haskell it has all props set to some value, probably:
- when proto-lens is doing encoding it omits default values 
- or, when tendermint RPC node encodes the message it omits keys which are set to default value.

**Comment by safareli** [comment]
> However, ideally they will make sure the swagger file is actually up to date and works, in which case we can just write the client library using the docs as a spec.

Yeah at least it can serve as a working docs.

~~I also opened this issue https://github.com/tendermint/tendermint/issues/3895, if it gets fixed, there swagger result would be nicer.~~

UPDATE: looks like the `URI over HTTP` protocol,  is for quick testing with curl

**Comment by martyall** [comment]
Yeah I was specifically saying this because for example at least all the ints should be there and be 0

> Because Response.Query is constructed in haskell it has all props set to some value, probably:

>when proto-lens is doing encoding it omits default values
or, when tendermint RPC node encodes the message it omits keys which are set to default value.

@safareli if you think this is the case , can you try to find out which ? It effects what we are even able to do about it

**Comment by charlescrain** [comment]
@safareli I think part of the problem was resolved here
https://github.com/f-o-a-m/hs-abci/pull/61/commits/48beac49ed758cf93fd445bb432c4e9bca9ee55c

We were attempting to decode `Either String Response.Query` instead of `Response.Query`

We still have the omit empty fields that parsing fails on but the `value` key is there.

**Comment by martyall** [comment]
Doh! 🤦‍♂ 

Ok forget what I said above about “it still doesn’t make sense ...”
