### ISSUE TITLE
investigate Application and Module level routers

### ISSUE THREAD

**Issue by martyall** [f-o-a-m/kepler#80]
We need an application router that can be used to handle application specific messages that come in (like the simple storage `UpdateCount` message).

In theory we could do something like the query router, but it seems like a way easier problem to solve if modules just have names and we assume that the messages are tagged with the module name, which seems to be the case with how the cosmos sdk works...

**Comment by charlescrain** [comment]
Makes sense since it doesn't really match the routing DSL in Servant. 

Could it be possible to use TH to create the module name spacing? I'd prefer to not leave avoiding collisions to the discretion of the developers as I imagine it could lead some tricky runtime errors. 

In addition to the module name spacing, it looks like its manually set in the codec for `Msg`s:

https://github.com/cosmos/cosmos-sdk/blob/5f9c3fdf88952ea43316f1a18de572e7ae3c13f6/x/bank/types/codec.go#L8

For both the `Msg`s and the module name maybe we could use type labels which could potentially avoid using TH. I'm not super familiar with labels but @blinky3713, I remember you used it in an earlier store implementation.

Sidenote: Queries also use the name module name, so we could integrate that in the queries as well.

**Comment by martyall** [comment]
Right now this is left intentionally vague in the nameservice application because there's only one module receiving messages at the moment.

I think eventually there will probably be some kind of `Module` type, maybe something like:

```haskell
data Module (name :: Symbol) msg queryApi r  = Module
  { moduleRouter :: msg -> Sem r ()
  , ...
  }
```

where we can probably created a router by some kind of `:<|>` like operation on modules. I haven't thought this part out entirely but we're getting close to being able to do that.

This would also help with nesting the query router to something like `name :> queryApi`

**Comment by martyall** [comment]
The issue will also include standardizing the modules router, which includes parsing module specific messages, doing any message specific validation, and dispatching the appropriate handler
